### ISSUE TITLE
Issue running the base command

### ISSUE THREAD

**Issue by ArianeMora** [EMCarrami/Pika#7]
Hi! I get the following issue when I try and run the suggested command: ` python run.py --config configs/train_config.json --run_mode train_and_benchmark`

```
Seed set to 1
Traceback (most recent call last):
  File "/disk1/ariane/pycharm/CARE/Pika/run.py", line 17, in <module>
    model = Pika(config)
  File "/disk1/ariane/pycharm/CARE/Pika/pika/main.py", line 41, in __init__
    self.model = PikaModel(**config["model"])
TypeError: PikaModel.__init__() got an unexpected keyword argument 'checkpoint'
```
This is a fresh install on a ubuntu, using the following to create the env:

```
yes | conda create --name pika python=3.10
pip install git+https://github.com/EMCarrami/Pika.git
```

**Comment by ArianeMora** [comment]
Fixed it by editing your `pika_model.py` and adding in the dummy param for `checkpoint`.

**Comment by EMCarrami** [comment]
Thank you for raising this issue. As a workaround, you can also remove the placeholder key for "checkpoint" in config.model

I have now fixed the code to handle this case, so a fresh install should work well.

**Comment by ArianeMora** [comment]
Thanks!
